Restrict Proxy Node alerts to the prod and integration namespaces
alphagov/prometheus-aws-configuration-beta pull request #348
Opened 2019-09-19 15:10 UTC by idrop

We're getting slack alerts when our gsp deployments are not healthy.

To ensure we care about these alerts, we should only get them for the integration and prod namespaces.

This PR will limit alerts to these namespaces.

2019-09-19 15:29 UTC, Wynndow approved these changes

2019-09-19 15:51 UTC, philandstuff requested changes
This will put the rest of them back into the default receiver (which is #re-autom8-alerts).  Could you add a rule that puts your uninteresting alerts into the `dev-null` receiver instead?

2019-09-20 09:46 UTC, tommrr approved these changes

2019-09-20 09:46 UTC, instantiator approved these changes

2019-09-20 10:15 UTC, philandstuff approved these changes

2019-09-20 10:15 UTC, merged